export const enum CardName {
  THE_FOOL = 'fool',
  THE_MAGICIAN = 'magician',
  THE_PRIESTESS = 'priestess',
  THE_EMPRESS = 'empress',
  THE_EMPEROR = 'emperor',
  THE_HIEROPHANT = 'hierophant',
  THE_LOVERS = 'lovers',
  THE_CHARIOT = 'chariot',
  STRENGTH = 'strength',
  THE_HERMIT = 'hermit',
  WHEEL_OF_FORTUNE = 'wheel_of_fortune',
  JUSTICE = 'justice',
  THE_HANGED_MAN = 'hanged_man',
  DEATH = 'death',
  TEMPERANCE = 'temperance',
  THE_DEVIL = 'devil',
  THE_TOWER = 'tower',
  THE_STAR = 'star',
  THE_MOON = 'moon',
  THE_SUN = 'sun',
  JUDGEMENT = 'judgement',
  THE_WORLD = 'world'
}

export const Russian: Record<`${CardName}`, string> = {
  'fool': 'Шут',
  'magician': 'Маг',
  'priestess': 'Верховная Жрица',
  'empress': 'Императрица',
  'emperor': 'Император',
  'hierophant': 'Иерофант',
  'lovers': 'Влюбленные',
  'chariot': 'Колесница',
  'strength': 'Сила',
  'hermit': 'Отшельник',
  'wheel_of_fortune': 'Колесо Фортуны',
  'justice': 'Справедливость',
  'hanged_man': 'Повешенный',
  'death': 'Смерть',
  'temperance': 'Умеренность',
  'devil': 'Дьявол',
  'tower': 'Башня',
  'star': 'Звезда',
  'moon': 'Луна',
  'sun': 'Солнце',
  'judgement': 'Суд',
  'world': 'Мир',
};
