import type { Theme } from '../model/types/questions';

import { SpreadType } from '@/entities/Spread';

export const THEMES: Theme[] = [
  {
    name: 'Anxiety and uncertainty',
    questions: [
      {
        label: 'General anxiety about the future',
        text: 'What awaits me in the coming months? Possible scenarios.',
        spreadTitle: 'Life horizon',
        spreadNumber: 7,
        spreadId: SpreadType.SEVEN,
        tariffs: {
          trial: false,
          standard: false,
          extended: true,
        },
      },
      {
        label: 'Fear of the unknown',
        text: 'What risks and opportunities lie ahead? How to prepare.',
        spreadTitle: 'The fog is clearing',
        spreadNumber: 5,
        spreadId: SpreadType.FIVE,
        tariffs: {
          trial: false,
          standard: true,
          extended: true,
        },
      },
      {
        label: 'Uncertainty in life',
        text: 'Why is everything unstable? What stabilizes the situation?',
        spreadTitle: 'Support in chaos',
        spreadNumber: 5,
        spreadId: SpreadType.FIVE,
        tariffs: {
          trial: false,
          standard: true,
          extended: true,
        },
      },
    ],
    isTemplate: true,
  },
  {
    name: 'Decision Making',
    questions: [
      {
        label: 'Choosing between options',
        text: 'Which path to choose? Pros and cons of each.',
        spreadTitle: 'Three roads',
        spreadNumber: 9,
        areDetailsNeeded: true,
        detailsQuestion: 'What are your options?',
        detailsAnswer: 'Your options',
        spreadId: SpreadType.NINE,
        tariffs: {
          trial: false,
          standard: false,
          extended: true,
        },
      },
      {
        label: 'Fear of making a mistake in decision',
        text: 'Is this the right move? Support from the Universe.',
        spreadTitle: 'Sign of fate',
        spreadNumber: 4,
        areDetailsNeeded: true,
        detailsQuestion: 'What is the decision about?',
        detailsAnswer: 'The decision',
        spreadId: SpreadType.FOUR,
        tariffs: {
          trial: false,
          standard: true,
          extended: true,
        },
      },
      {
        label: 'Passing the buck',
        text: 'What do the cards advise to do in this situation?',
        spreadTitle: 'Advice of the sage',
        spreadNumber: 3,
        areDetailsNeeded: true,
        detailsQuestion: 'What is the situation?',
        detailsAnswer: 'The situation',
        spreadId: SpreadType.THREE,
        tariffs: {
          trial: false,
          standard: false,
          extended: true,
        },
      },
    ],
    isTemplate: true,
  },
  {
    name: 'Relationships and love',
    questions: [
      {
        label: 'Love and relationships now',
        text: "What's going on between me and my partner? Feelings, motives.",
        spreadTitle: 'Relationship triangle',
        spreadNumber: 3,
        spreadId: SpreadType.THREE,
        tariffs: {
          trial: false,
          standard: true,
          extended: true,
        },
      },
      {
        label: "The couple's future",
        text: 'Is there a chance for our relationship? What lies ahead.',
        spreadTitle: 'The path of love',
        spreadNumber: 7,
        spreadId: SpreadType.SEVEN,
        tariffs: {
          trial: false,
          standard: false,
          extended: true,
        },
      },
      {
        label: 'Returning to an ex',
        text: "Should I return it? Partner's thoughts, conclusion.",
        spreadTitle: 'Bridge back',
        spreadNumber: 5,
        spreadId: SpreadType.FIVE,
        tariffs: {
          trial: false,
          standard: true,
          extended: true,
        },
      },
      {
        label: 'Dating a new person',
        text: 'How does he(she) feel? Prospects.',
        spreadTitle: 'Chemistry at the start',
        spreadNumber: 4,
        spreadId: SpreadType.FOUR,
        tariffs: {
          trial: false,
          standard: true,
          extended: true,
        },
      },
      {
        label: 'Scenarios in love',
        text: 'Why do mistakes repeat themselves? How to break the cycle.',
        spreadTitle: 'Karmic love',
        spreadNumber: 5,
        areDetailsNeeded: true,
        detailsQuestion: 'What are the mistakes you want to fix?',
        detailsAnswer: 'Mistakes I want to fix',
        spreadId: SpreadType.FIVE,
        tariffs: {
          trial: false,
          standard: true,
          extended: true,
        },
      },
      {
        label: 'Compatibility',
        text: 'Are we a good fit? Strengths/Weaknesses.',
        spreadTitle: 'Two decks',
        spreadNumber: 6,
        spreadId: SpreadType.TWO_DECKS,
        tariffs: {
          trial: false,
          standard: false,
          extended: true,
        },
      },
      {
        label: 'Breakup',
        text: 'Am I leaving correctly? How to let go.',
        spreadTitle: 'The door is closed',
        spreadNumber: 6,
        spreadId: SpreadType.SIX,
        tariffs: {
          trial: false,
          standard: false,
          extended: true,
        },
      },
      {
        label: 'Loneliness and "the one"',
        text: "When will I meet my partner? What's blocking me?",
        spreadTitle: 'Star of love',
        spreadNumber: 7,
        spreadId: SpreadType.SEVEN,
        tariffs: {
          trial: false,
          standard: false,
          extended: true,
        },
      },
      {
        label: 'Cheating and betrayal"',
        text: 'Is there a third party? What to do.',
        spreadTitle: 'Mystery revealed',
        spreadNumber: 6,
        spreadId: SpreadType.SIX,
        tariffs: {
          trial: false,
          standard: false,
          extended: true,
        },
      },
      {
        label: 'Crisis in a couple',
        text: 'What destroys? How to restore.',
        spreadTitle: 'Storm in a relationship',
        spreadNumber: 7,
        spreadId: SpreadType.SEVEN,
        tariffs: {
          trial: false,
          standard: false,
          extended: true,
        },
      },
      {
        label: 'Self-esteem in love',
        text: 'Why do I choose the "wrong ones"? How to love yourself.',
        spreadTitle: 'Mirror of the Soul',
        spreadNumber: 7,
        areDetailsNeeded: true,
        detailsQuestion: 'Why do you think you choose the "wrong ones"?',
        detailsAnswer: 'I choose the "wrong ones because',
        spreadId: SpreadType.SEVEN,
        tariffs: {
          trial: false,
          standard: false,
          extended: true,
        },
      },
    ],
    isTemplate: true,
  },
  {
    name: 'Work, career, self-realization',
    questions: [
      {
        label: 'Change of profession',
        text: 'Where to go? Is this "my" job?',
        spreadTitle: 'Career turnaround',
        spreadNumber: 7,
        areDetailsNeeded: true,
        detailsQuestion: 'What is your current profession?',
        detailsAnswer: 'My current profession',
        spreadId: SpreadType.SEVEN,
        tariffs: {
          trial: false,
          standard: false,
          extended: true,
        },
      },
      {
        label: 'Finding your "thing"',
        text: 'What are my talents? Where can I find fulfillment?',
        spreadTitle: 'Call of Destiny',
        spreadNumber: 6,
        spreadId: SpreadType.SIX,
        tariffs: {
          trial: false,
          standard: false,
          extended: true,
        },
      },
      {
        label: 'Doubts about offers',
        text: 'Which offer to choose? The risks of each.',
        spreadTitle: 'Two jobs',
        spreadNumber: 5,
        areDetailsNeeded: true,
        detailsQuestion: 'What are the offers you are considering?',
        detailsAnswer: 'The offers I am considering are',
        spreadId: SpreadType.FIVE,
        tariffs: {
          trial: false,
          standard: true,
          extended: true,
        },
      },
    ],
    isTemplate: true,
  },
  {
    name: 'Money and business',
    questions: [
      {
        label: 'Launching a project/business',
        text: "What's hindering growth? Strategy adjustments.",
        spreadTitle: 'Business Impulse',
        spreadNumber: 7,
        areDetailsNeeded: true,
        detailsQuestion: 'What is your current business?',
        detailsAnswer: 'My current business',
        spreadId: SpreadType.SEVEN,
        tariffs: {
          trial: false,
          standard: false,
          extended: true,
        },
      },
      {
        label: 'Blind spots in the project',
        text: 'Obstacles, resources, growth points.',
        spreadTitle: 'Business diagnosis',
        spreadNumber: 9,
        spreadId: SpreadType.NINE,
        tariffs: {
          trial: false,
          standard: false,
          extended: true,
        },
      },
      {
        label: 'Risk assessment',
        text: 'Investment/Partnership Risks? Summary.',
        spreadTitle: 'Weighing the odds',
        spreadNumber: 5,
        spreadId: SpreadType.FIVE,
        tariffs: {
          trial: false,
          standard: true,
          extended: true,
        },
      },
    ],
    isTemplate: true,
  },
  {
    name: 'Self-knowledge and crises',
    questions: [
      {
        label: 'Stuck on autopilot',
        text: 'What are my true desires? What needs to be changed?',
        spreadTitle: 'Awakening',
        spreadNumber: 6,
        spreadId: SpreadType.SIX,
        tariffs: {
          trial: false,
          standard: false,
          extended: true,
        },
      },
      {
        label: 'Search for wishes',
        text: 'What do I really want?',
        spreadTitle: 'The heart speaks',
        spreadNumber: 4,
        spreadId: SpreadType.FOUR,
        tariffs: {
          trial: false,
          standard: true,
          extended: true,
        },
      },
      {
        label: 'Crises of meaning/age',
        text: 'The logic of my story? New meaning.',
        spreadTitle: 'Puzzle of life',
        spreadNumber: 7,
        spreadId: SpreadType.SEVEN,
        tariffs: {
          trial: false,
          standard: false,
          extended: true,
        },
      },
    ],
    isTemplate: true,
  },
  {
    name: 'Emotional relief',
    questions: [
      {
        label: 'Speak out through cards',
        text: 'What hurts inside? A gentle analysis.',
        spreadTitle: 'A heart-to-heart talk',
        spreadNumber: 5,
        spreadId: SpreadType.FIVE,
        tariffs: {
          trial: false,
          standard: false,
          extended: true,
        },
      },
      {
        label: 'Name feelings',
        text: 'What do I feel? How to experience',
        spreadTitle: 'Emotions in the open',
        spreadNumber: 3,
        spreadId: SpreadType.THREE,
        tariffs: {
          trial: false,
          standard: true,
          extended: true,
        },
      },
    ],
    isTemplate: true,
  },
  {
    name: 'Spirituality and the Path',
    questions: [
      {
        label: 'Connection to the Greater',
        text: 'My path, signs of the Universe.',
        spreadTitle: 'Spiritual compass',
        spreadNumber: 5,
        spreadId: SpreadType.FIVE,
        tariffs: {
          trial: false,
          standard: true,
          extended: true,
        },
      },
      {
        label: 'Meanings of events',
        text: 'Why did this happen to me?',
        spreadTitle: 'Lesson of fate',
        spreadNumber: 6,
        spreadId: SpreadType.SIX,
        tariffs: {
          trial: false,
          standard: false,
          extended: true,
        },
      },
    ],
    isTemplate: true,
  },
  {
    name: 'Rituals of transformation',
    questions: [
      {
        label: 'New stage of life',
        text: 'Support at the start: moving, year, relationships.',
        spreadTitle: 'New moon',
        spreadNumber: 7,
        spreadId: SpreadType.SEVEN,
        tariffs: {
          trial: false,
          standard: false,
          extended: true,
        },
      },
      {
        label: 'Completing the cycle',
        text: 'What to let go of? What to take into the new.',
        spreadTitle: 'Liberation',
        spreadNumber: 4,
        spreadId: SpreadType.FOUR,
        tariffs: {
          trial: false,
          standard: true,
          extended: true,
        },
      },
    ],
    isTemplate: true,
  },
  {
    name: 'Intuition vs. rationality',
    questions: [
      {
        label: 'Intuitive advice',
        text: 'What does your gut tell you? Symbols.',
        spreadTitle: 'The voice of intuition',
        spreadNumber: 3,
        spreadId: SpreadType.THREE,
        tariffs: {
          trial: false,
          standard: true,
          extended: true,
        },
      },
      {
        label: 'Figurative language',
        text: 'Metaphors for my questions.',
        spreadTitle: 'Tale of cards',
        spreadNumber: 5,
        spreadId: SpreadType.FIVE,
        tariffs: {
          trial: false,
          standard: true,
          extended: true,
        },
      },
    ],
    isTemplate: true,
  },
  {
    name: 'My own question',
    questions: [],
    isTemplate: false,
  },
];
