import { CardName } from '@/shared/types/arcana';

export const ALL_TAROT_CARDS_ARRAY = [
  // Старший Аркан (22 карты)
  CardName.THE_FOOL,
  CardName.THE_MAGICIAN,
  CardName.THE_HIGH_PRIESTESS,
  CardName.THE_EMPRESS,
  CardName.THE_EMPEROR,
  CardName.THE_HIEROPHANT,
  CardName.THE_LOVERS,
  CardName.THE_CHARIOT,
  CardName.STRENGTH,
  CardName.THE_HERMIT,
  CardName.WHEEL_OF_FORTUNE,
  CardName.JUSTICE,
  CardName.THE_HANGED_MAN,
  CardName.DEATH,
  CardName.TEMPERANCE,
  CardName.THE_DEVIL,
  CardName.THE_TOWER,
  CardName.THE_STAR,
  CardName.THE_MOON,
  CardName.THE_SUN,
  CardName.JUDGEMENT,
  CardName.THE_WORLD,

  // Жезлы (14 карт)
  CardName.ACE_OF_WANDS,
  CardName.TWO_OF_WANDS,
  CardName.THREE_OF_WANDS,
  CardName.FOUR_OF_WANDS,
  CardName.FIVE_OF_WANDS,
  CardName.SIX_OF_WANDS,
  CardName.SEVEN_OF_WANDS,
  CardName.EIGHT_OF_WANDS,
  CardName.NINE_OF_WANDS,
  CardName.TEN_OF_WANDS,
  CardName.PAGE_OF_WANDS,
  CardName.KNIGHT_OF_WANDS,
  CardName.QUEEN_OF_WANDS,
  CardName.KING_OF_WANDS,

  // Кубки (14 карт)
  CardName.ACE_OF_CUPS,
  CardName.TWO_OF_CUPS,
  CardName.THREE_OF_CUPS,
  CardName.FOUR_OF_CUPS,
  CardName.FIVE_OF_CUPS,
  CardName.SIX_OF_CUPS,
  CardName.SEVEN_OF_CUPS,
  CardName.EIGHT_OF_CUPS,
  CardName.NINE_OF_CUPS,
  CardName.TEN_OF_CUPS,
  CardName.PAGE_OF_CUPS,
  CardName.KNIGHT_OF_CUPS,
  CardName.QUEEN_OF_CUPS,
  CardName.KING_OF_CUPS,

  // Мечи (14 карт)
  CardName.ACE_OF_SWORDS,
  CardName.TWO_OF_SWORDS,
  CardName.THREE_OF_SWORDS,
  CardName.FOUR_OF_SWORDS,
  CardName.FIVE_OF_SWORDS,
  CardName.SIX_OF_SWORDS,
  CardName.SEVEN_OF_SWORDS,
  CardName.EIGHT_OF_SWORDS,
  CardName.NINE_OF_SWORDS,
  CardName.TEN_OF_SWORDS,
  CardName.PAGE_OF_SWORDS,
  CardName.KNIGHT_OF_SWORDS,
  CardName.QUEEN_OF_SWORDS,
  CardName.KING_OF_SWORDS,

  // Пентакли (14 карт)
  CardName.ACE_OF_COINS,
  CardName.TWO_OF_COINS,
  CardName.THREE_OF_COINS,
  CardName.FOUR_OF_COINS,
  CardName.FIVE_OF_COINS,
  CardName.SIX_OF_COINS,
  CardName.SEVEN_OF_COINS,
  CardName.EIGHT_OF_COINS,
  CardName.NINE_OF_COINS,
  CardName.TEN_OF_COINS,
  CardName.PAGE_OF_COINS,
  CardName.KNIGHT_OF_COINS,
  CardName.QUEEN_OF_COINS,
  CardName.KING_OF_COINS
] as const;
