export const ABOUT_ARCANES = {
  title: 'Arcanes',
  paragraphs: [
    'The Fool',
    'Meanings — beginning of a journey, risk, potential, naivety.',
    'The Fool is intended for new beginnings, expanding horizons and using the chance suggested by intuition. This card also indicates naivety and excitement about the unknown.',
    'Card No. 1: The Magician',
    'Meanings — manifestation, healing, spirituality, connection with the divine.',
    'The Magician represents the ability to understand and control invisible forces of the Universe. In a spread, this card indicates a special gift of a person that has not yet been used.',
    'Card No. 2: The High Priestess',
    'Meanings — divine feminine principle, human wisdom, study of nature, spiritual mystery, inner world.',
    'The High Priestess symbolizes the feminine spiritual principle, endows with it, and in case of loss of such energy, absorbs it back into herself.',
    'Card No. 3: The Empress',
    'Meanings — nature, great mother, fertility.',
    'The Empress, in contrast to the divinity of the High Priestess, represents the natural feminine principle, symbol of the mother of all.',
    'Card No. 4: The Emperor',
    'Meanings — leadership, influence, stability, potential for mastery.',
    'If the Empress is the figure of mother, then the Emperor is father. He symbolizes primacy, strength and power in nature, and must be reckoned with.',
    'Card No. 5: The Hierophant',
    'Meanings — practical lessons related to natural law, learning, mastering chosen field of knowledge.',
    'The Hierophant is as powerful as the Emperor, but tends to draw strength not from nature, but from the spiritual. Sometimes indicates the desire to break free from limitations to follow the divine path.',
    'Card No. 6: The Lovers',
    'Meanings — difficult decisions, changes in relationships, compromise.',
    'The Lovers speak of deep intimacy, reminding that relationships give a person value.',
    'Card No. 7: The Chariot',
    'Meanings — controlling opposing forces, resolving conflict, willpower, journey.',
    'The Chariot represents control over internal contradictions. It may also indicate the possibility of travel.',
    'Card No. 8: Strength',
    'Meanings — need for discipline, clarifying personal interests to achieve harmony with inner "self".',
    'Strength is depicted as a woman gently controlling a powerful lion. The card means inner strength, overcoming weaknesses, courage and perseverance. In some interpretations, it is also viewed as a symbol of fighting animal nature or harmony with instincts.',
    'Card No. 9: The Hermit',
    'Meanings — self-analysis, contemplation, inner reflection, benefit of time spent alone.',
    'The Hermit is turning inward, reflecting, often in solitude. The card is associated with inner wisdom, self-assessment, often calls for self-analysis. Moreover, The Hermit in a spread may hint that there is a guide nearby offering help.',
    'Card No. 10: Wheel of Fortune',
    'Meanings — inevitable and often positive transformations, cycles of life, beginning and end.',
    'Wheel of Fortune symbolizes the inevitability of change, starting and ending points. Also indicates crossroads of fate when choosing breaks patterns.',
    'Card No. 11: Justice',
    'Meanings — justice, moral sensitivity, karma, attention to detail.',
    'Justice is truth, balance and objectivity. Emotional equilibrium follows correct choice, even if it is difficult.',
    'Card No. 12: The Hanged Man',
    'Meanings — consequences, stagnation, situation that needs to be endured.',
    'The Hanged Man symbolizes sacrifice and the need to look at things from a different perspective. In a spread, it may call for surrender or abandoning patterned actions.',
    'Card No. 13: Death',
    'Meanings — ending, moving forward, personal liberation.',
    'Death looks ominous, but does not prophesy actual death of a person. This is a card of change that mostly occurs during personal growth when we free ourselves from old behavioral patterns. Death indicates necessary reset to continue the journey.',
    'Card No. 14: Temperance',
    'Meanings — balance, self-development.',
    'Temperance means self-improvement and avoiding extremes. It appears in a spread when a person is not in harmony with himself. The main meaning of the card is to suggest restoring balance.',
    'Card No. 15: The Devil',
    'Meanings — trap, unhealthy relationships, material pleasures.',
    "The Devil speaks of inner demons. This card often appears when unhealthy behavioral patterns are activated, whether it's failed relationships, negative self-talk, or addictions.",
    'Card No. 16: The Tower',
    'Meanings — possible or real danger, unexpected upheaval.',
    'The Tower is one of the most ominous cards, as it usually foretells serious changes, destruction and even threats. It symbolizes chaos, as well as approaching a dramatic end.',
    'Card No. 17: The Star',
    'Meanings — spirituality, purpose, connection with the divine, excellence, inspiration.',
    'The Star carries a deep and powerful message, especially for those experiencing rebirth. After stress or destruction, it asks to spend time on self-analysis and heal wounds.',
    'Card No. 18: The Moon',
    'Meanings — illusion, impressionability, deception, confusion, discord.',
    'The Moon speaks of a good time for deep work with the subconscious, of readiness to see and accept the real self. The card calls to free emotions from control to reach the most precious inside oneself.',
    'Card No. 19: The Sun',
    'Meanings — vitality, joy, luck, confidence, authenticity.',
    'The Sun is one of the most positive cards. It symbolizes happiness, success, pleasure, self-expression and life force.',
    'Card No. 20: Judgement',
    'Meanings — resurrection, awakening, necessity of making decisions.',
    'Judgement refers to Christianity: on Judgment Day God will reveal the righteous and sinners, reward or punish. This card awakens to make corrections in life.',
    'Card No. 21: The World',
    'Meanings — end of cycle, significant change, self-realization.',
    'The World is a big step forward, a card of absorbing lessons and wisdom. It indicates new understanding of life and role in it, speaks of personal growth and brings satisfaction.',
    'Major Arcana shows your life from the side through the journey of the Fool. At the same time, it is not so much the number of the drawn card that matters, but what you decide to do with its lesson in your own spiritual journey.',
  ],
};
