export const enum CardName {
  // Старший Аркан
  THE_FOOL = 'fool',
  THE_MAGICIAN = 'magician',
  THE_HIGH_PRIESTESS = 'high_priestess',
  THE_EMPRESS = 'empress',
  THE_EMPEROR = 'emperor',
  THE_HIEROPHANT = 'hierophant',
  THE_LOVERS = 'lovers',
  THE_CHARIOT = 'chariot',
  STRENGTH = 'strength',
  THE_HERMIT = 'hermit',
  WHEEL_OF_FORTUNE = 'wheel_of_fortune',
  JUSTICE = 'justice',
  THE_HANGED_MAN = 'hanged_man',
  DEATH = 'death',
  TEMPERANCE = 'temperance',
  THE_DEVIL = 'devil',
  THE_TOWER = 'tower',
  THE_STAR = 'star',
  THE_MOON = 'moon',
  THE_SUN = 'sun',
  JUDGEMENT = 'judgement',
  THE_WORLD = 'world',

  // Жезлы
  ACE_OF_WANDS = 'ace_of_wands',
  TWO_OF_WANDS = 'two_of_wands',
  THREE_OF_WANDS = 'three_of_wands',
  FOUR_OF_WANDS = 'four_of_wands',
  FIVE_OF_WANDS = 'five_of_wands',
  SIX_OF_WANDS = 'six_of_wands',
  SEVEN_OF_WANDS = 'seven_of_wands',
  EIGHT_OF_WANDS = 'eight_of_wands',
  NINE_OF_WANDS = 'nine_of_wands',
  TEN_OF_WANDS = 'ten_of_wands',
  PAGE_OF_WANDS = 'page_of_wands',
  KNIGHT_OF_WANDS = 'knight_of_wands',
  QUEEN_OF_WANDS = 'queen_of_wands',
  KING_OF_WANDS = 'king_of_wands',

  // Кубки
  ACE_OF_CUPS = 'ace_of_cups',
  TWO_OF_CUPS = 'two_of_cups',
  THREE_OF_CUPS = 'three_of_cups',
  FOUR_OF_CUPS = 'four_of_cups',
  FIVE_OF_CUPS = 'five_of_cups',
  SIX_OF_CUPS = 'six_of_cups',
  SEVEN_OF_CUPS = 'seven_of_cups',
  EIGHT_OF_CUPS = 'eight_of_cups',
  NINE_OF_CUPS = 'nine_of_cups',
  TEN_OF_CUPS = 'ten_of_cups',
  PAGE_OF_CUPS = 'page_of_cups',
  KNIGHT_OF_CUPS = 'knight_of_cups',
  QUEEN_OF_CUPS = 'queen_of_cups',
  KING_OF_CUPS = 'king_of_cups',

  // Мечи
  ACE_OF_SWORDS = 'ace_of_swords',
  TWO_OF_SWORDS = 'two_of_swords',
  THREE_OF_SWORDS = 'three_of_swords',
  FOUR_OF_SWORDS = 'four_of_swords',
  FIVE_OF_SWORDS = 'five_of_swords',
  SIX_OF_SWORDS = 'six_of_swords',
  SEVEN_OF_SWORDS = 'seven_of_swords',
  EIGHT_OF_SWORDS = 'eight_of_swords',
  NINE_OF_SWORDS = 'nine_of_swords',
  TEN_OF_SWORDS = 'ten_of_swords',
  PAGE_OF_SWORDS = 'page_of_swords',
  KNIGHT_OF_SWORDS = 'knight_of_swords',
  QUEEN_OF_SWORDS = 'queen_of_swords',
  KING_OF_SWORDS = 'king_of_swords',

  // Пентакли
  ACE_OF_COINS = 'ace_of_coins',
  TWO_OF_COINS = 'two_of_coins',
  THREE_OF_COINS = 'three_of_coins',
  FOUR_OF_COINS = 'four_of_coins',
  FIVE_OF_COINS = 'five_of_coins',
  SIX_OF_COINS = 'six_of_coins',
  SEVEN_OF_COINS = 'seven_of_coins',
  EIGHT_OF_COINS = 'eight_of_coins',
  NINE_OF_COINS = 'nine_of_coins',
  TEN_OF_COINS = 'ten_of_coins',
  PAGE_OF_COINS = 'page_of_coins',
  KNIGHT_OF_COINS = 'knight_of_coins',
  QUEEN_OF_COINS = 'queen_of_coins',
  KING_OF_COINS = 'king_of_coins'
};
